      ; // investor profile page
      // 'investor-profile-title': 'الملف الشخصي للمستثمر - منصة مستثمر',
      // 'home-page': 'الرئيسية',
      // 'dashboard': 'لوحة التحكم',
      // 'browse-projects': 'استعرض المشاريع',
      // 'my-projects': 'مشاريعي',
      // 'add-project': 'أضف مشروع',
      // 'investor-name': 'أحمد محمد',
      // 'investor-bio': 'مستثمر في قطاع التقنية مهتم بالمشاريع الناشئة في مجال الذكاء الاصطناعي والتعليم الإلكتروني',
      // 'investor-email': 'ahmed.investor@example.com',
      // 'investor-phone': '+966 50 123 4567',
      // 'investor-linkedin': 'LinkedIn.com/ahmed-investor',
      // 'edit-profile': 'تعديل الملف الشخصي',
      // 'investment-portfolio': 'محفظة الاستثمارات',
      // 'total-investments': 'إجمالي الاستثمارات',
      // 'total-investments-value': '1,250,000 ريال',
      // 'total-profit': 'الأرباح',
      // 'total-profit-value': '150,000 ريال',
      // 'expected-returns': 'العوائد المتوقعة',
      // 'expected-returns-value': '200,000 ريال',
      // 'project-name-1': 'مشروع منصة تعليمية مبتكرة',
      // 'project-status-1': 'نشط',
      // 'project-name-2': 'تطبيق توصيل طلبات سريع',
      // 'project-status-2': 'الحالة: متابعة | مبلغ الاستثمار: 100,000 ريال | عائد متوقع: 20%',
      // 'view-details': 'عرض التفاصيل',
      // 'investment-opportunities': 'فرص الاستثمار',
      // 'opportunity-name-1': 'حلول طاقة شمسية مبتكرة',
      // 'opportunity-desc-1': 'مشروع يهدف إلى توفير حلول طاقة شمسية مستدامة للمنازل والشركات.',
      // 'opportunity-name-2': 'منصة ذكاء اصطناعي للرعاية الصحية',
      // 'opportunity-desc-2': 'تطوير منصة تعتمد على الذكاء الاصطناعي لتحسين تشخيص الأمراض.',
      // 'express-interest': 'التعبير عن الاهتمام',
      // 'communication': 'التواصل',
      // 'recent-messages': 'الرسائل الأخيرة',
      // 'message-1': 'رسالة جديدة من حامل فكرة مشروع التقنية المالية',
      // 'message-time-1': 'منذ ساعتين',
      // 'message-2': 'طلب اجتماع لمناقشة تفاصيل الاستثمار',
      // 'message-time-2': 'منذ يوم واحد',
      // 'notifications': 'الإشعارات',
      // 'notification-1': 'تحديث جديد على مشروع منصة التعليم المبتكرة',
      // 'notification-time-1': 'منذ 3 ساعات',
      // 'notification-2': 'فرصة استثمارية جديدة متاحة في قطاع التكنولوجيا',
      // 'notification-time-2': 'منذ يومين',
      // 'account-settings': 'إعدادات الحساب',
      // 'notification-preferences': 'تفضيلات التنبيهات',
      // 'privacy-settings': 'إعدادات الخصوصية',
      // 'password-management': 'إدارة كلمة المرور',
      // 'manage': 'إدارة',
      // 'change': 'تغيير',
      // 'educational-resources': 'موارد تعليمية',
      // 'resource-title-1': 'دليل الاستثمار للمبتدئين',
      // 'resource-desc-1': 'تعلم أساسيات الاستثمار وكيفية تقييم المشاريع الناشئة.',
      // 'resource-title-2': 'نصائح إدارة المخاطر',
      // 'resource-desc-2': 'استراتيجيات فعالة لتقليل المخاطر وزيادة العوائد.',
      // 'read-more': 'اقرأ المزيد',
      // 'footer-text': '© 2024 منصة مستثمر. جميع الحقوق محفوظة.',
      // 'view-all-messages': 'عرض الكل',
      // 'view-all-notifications': 'عرض الكل',
      // 'browse-more': 'تصفح المزيد',
      // 'view-project-details': 'عرض تفاصيل المشروع',
      ; // Statistics
      // 'stats-title': 'Platform Statistics',
      // 'stats-projects': 'Projects',
      // 'stats-investors': 'Investors',
      // 'stats-funded': 'Funded Projects',

       // investor profile page
      // 'investor-profile-title': 'Investor Profile - Mostathmir Platform',
      // 'home-page': 'Home',
      // 'dashboard': 'Dashboard',
      // 'browse-projects': 'Browse Projects',
      // 'my-projects': 'My Projects',
      // 'add-project': 'Add Project',
      // 'investor-name': 'Ahmed Mohammed',
      // 'investor-bio': 'Technology sector investor interested in startups in AI and e-learning',
      // 'investor-email': 'ahmed.investor@example.com',
      // 'investor-phone': '+966 50 123 4567',
      // 'investor-linkedin': 'LinkedIn.com/ahmed-investor',
      // 'edit-profile': 'Edit Profile',
      // 'investment-portfolio': 'Investment Portfolio',
      // 'total-investments': 'Total Investments',
      // 'total-investments-value': 'SAR 1,250,000',
      // 'total-profit': 'Profits',
      // 'total-profit-value': 'SAR 150,000',
      // 'expected-returns': 'Expected Returns',
      // 'expected-returns-value': 'SAR 200,000',
      // 'project-name-1': 'Innovative Educational Platform Project',
      // 'project-status-1': 'Active ',
      // 'project-name-2': 'Fast Delivery App',
      // 'project-status-2': 'Status: Monitoring | Investment: SAR 100,000 | Expected Return: 20%',
      // 'view-details': 'View Details',
      // 'investment-opportunities': 'Investment Opportunities',
      // 'opportunity-name-1': 'Innovative Solar Energy Solutions',
      // 'opportunity-desc-1': 'Project aimed at providing sustainable solar energy solutions for homes and businesses.',
      // 'opportunity-name-2': 'AI Healthcare Platform',
      // 'opportunity-desc-2': 'Developing an AI-based platform to improve disease diagnosis.',
      // 'express-interest': 'Express Interest',
      // 'communication': 'Communication',
      // 'recent-messages': 'Recent Messages',
      // 'message-1': 'New message from fintech project idea holder',
      // 'message-time-1': '2 hours ago',
      // 'message-2': 'Meeting request to discuss investment details',
      // 'message-time-2': '1 day ago',
      // 'notifications': 'Notifications',
      // 'notification-1': 'New update on innovative education platform project',
      // 'notification-time-1': '3 hours ago',
      // 'notification-2': 'New investment opportunity available in technology sector',
      // 'notification-time-2': '2 days ago',
      // 'account-settings': 'Account Settings',
      // 'notification-preferences': 'Notification Preferences',
      // 'privacy-settings': 'Privacy Settings',
      // 'password-management': 'Password Management',
      // 'manage': 'Manage',
      // 'change': 'Change',
      // 'educational-resources': 'Educational Resources',
      // 'resource-title-1': 'Investment Guide for Beginners',
      // 'resource-desc-1': 'Learn investment basics and how to evaluate startups.',
      // 'resource-title-2': 'Risk Management Tips',
      // 'resource-desc-2': 'Effective strategies to reduce risks and increase returns.',
      // 'read-more': 'Read More',
      // 'footer-text': '© 2024 Mostathmir Platform. All rights reserved.',
      // 'view-all-messages': 'View All',
      // 'view-all-notifications': 'View All',
      // 'browse-more': 'Browse More',
      // 'view-project-details': 'View Project Details',